name: Typst build check

on:
  pull_request:
    branches: [ main ]
    paths:
      - "*.typ"
      - "**/*.typ"
      - ".github/workflows/typst-check.yml"
  push:
    branches: [ main ]
    paths:
      - "*.typ"
      - "**/*.typ"
      - ".github/workflows/typst-check.yml"

jobs:
  build:
    name: Compile Typst files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: latest

      - name: Find Typst files
        id: targets
        run: |
          set -e
          mkdir -p build
          mapfile -t FILES < <(git ls-files '*.typ' '**/*.typ' | grep -v '^_' | grep -v '/_')
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "targets=" >> "$GITHUB_OUTPUT"
          else
            {
              echo 'targets<<EOF'
              printf '%s\n' "${FILES[@]}"
              echo 'EOF'
            } >> "$GITHUB_OUTPUT"
          fi

      - name: Compile Typst files
        if: steps.targets.outputs.targets != ''
        run: |
          set -e
          mkdir -p build

          # Require main.typ to exist
          if [ ! -f "main.typ" ]; then
            echo "main.typ not found in repository root"
            exit 1
          fi

          echo "Compiling main.typ -> build/main.pdf"
          typst compile main.typ build/main.pdf

          FILES="${{ steps.targets.outputs.targets }}"

          # Compile all other .typ files (one per line; handle spaces)
          while IFS= read -r f; do
            [[ -z "$f" || "$f" != *.typ || "$f" == "main.typ" ]] && continue
            out="build/${f%.typ}.pdf"
            mkdir -p "$(dirname "$out")"
            echo "Compiling $f -> $out"
            typst compile "$f" "$out"
          done <<< "$FILES"
          
      - name: Upload PDF compiled from main.typ
        if: steps.targets.outputs.targets != ''
        uses: actions/upload-artifact@v4
        with:
          name: typst-main-pdf
          path: build/main.pdf
